version: '3.3'
services:
  rabbitmq1:
    build: ./var/rabbitmq
    hostname: rabbitmq1
    ports:  
    - "1883:1883"
    - "5672:5672"
    - "5552:5552"
    - "15672:15672"
    - "15692:15692"
    - "61613:61613"
    volumes:
      - ./var/rabbitmq:/export
      - .erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    env_file: .env
  rabbitmq2:
    build: ./var/rabbitmq
    hostname: rabbitmq2
    ports:
    - "1884:1883"
    - "5673:5672"
    - "5553:5552"
    - "15673:15672"
    - "15693:15692"
    - "61614:61613"
    volumes:
      - ./var/rabbitmq:/export
      - .erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    env_file: .env
  rabbitmq3:
    build: ./var/rabbitmq
    hostname: rabbitmq3
    ports:
    - "1885:1883"
    - "5674:5672"
    - "5554:5552"
    - "15674:15672"
    - "15694:15692"
    - "61615:61613"
    volumes:
      - ./var/rabbitmq:/export
      - .erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    env_file: .env
  prometheus:
    image: prom/prometheus:v2.35.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    ports:
    - '9090:9090'
    links:
      - rabbitmq1:rabbitmq1
      - rabbitmq2:rabbitmq2
      - rabbitmq3:rabbitmq3
    volumes:
      - ./var/data/prometheus:/prometheus
      - ./var/prometheus/config:/etc/prometheus
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./var/data/grafana:/var/lib/grafana
      - ./var/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./var/grafana/config.monitoring
